# Generated by Django 4.2.1 on 2023-05-31 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Students_data',
        ),
    ]
